name: Build and Deploy FrontEnd

on:
  push:
    branches:
      - main

jobs:

  dockerhub-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Update JavaScript version in index.html
      run: |
        sed -i 's/__WORKFLOW_RUN_NUMBER__/${{ github.run_number }}/g' ./dist/index.html
        sed -i 's/__WORKFLOW_RUN_NUMBER__/${{ github.run_number }}/g' index.html

    - name: Login into docker
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Set up Docker Build and Push
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags:
          copapel/funil_vendas_frontend:latest


  portainer-deploy:
    needs: dockerhub-push
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios https dotenv

      - name: Run Portainer deploy script
        run: node ./portainer-deploy-script.js
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
          NOME_IMAGEM: ${{ secrets.NOME_IMAGEM }}







        
